import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any
from src.core.models import EOBDocument, AuditResult, AppealPacket

class ERISAAppealGenerator:
    """
    Statutory Appeal Document Compiler.
    Synthesizes formal, legally structured ERISA § 503 and No Surprises Act appeal letters
    grounded in deterministic CMS NCCI audit findings.
    """

    @staticmethod
    def compile_appeal_packet(eob: EOBDocument, audit: AuditResult, cedar_verified: bool = False) -> AppealPacket:
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
        packet_id = f"APPEAL-ERISA-{uuid.uuid4().hex[:8].upper()}"

        citations = [
            "ERISA § 503 (29 U.S.C. § 1133) - Full and Fair Review of Adverse Benefit Determinations",
            "29 CFR § 2560.503-1(g) - Mandatory Disclosure of Specific Internal Rules and Guidelines",
            "Centers for Medicare & Medicaid Services (CMS) NCCI Policy Manual, Chapter 1"
        ]

        if not eob.in_network or eob.is_emergency:
            citations.append("45 CFR § 149.30 (No Surprises Act) - Prohibition on Surprise Out-of-Network Balance Billing")

        evidence_breakdown: List[Dict[str, Any]] = []
        for v in audit.violations:
            evidence_breakdown.append({
                "violation_type": v.violation_type.value,
                "line_number": v.line_number,
                "primary_cpt": v.primary_code,
                "secondary_cpt": v.secondary_code,
                "excised_overcharge": v.excised_amount,
                "statutory_authority": v.statutory_reference,
                "clinical_finding": v.explanation
            })

        # Formal legal dispute letter
        violations_text = ""
        for idx, v in enumerate(audit.violations, 1):
            violations_text += (
                f"  {idx}. [Line {v.line_number}] Violation: {v.violation_type.value}\n"
                f"     Procedure Codes: {v.primary_code}"
                + (f" / {v.secondary_code}" if v.secondary_code else "")
                + f"\n     Disputed Amount: ${v.excised_amount:,.2f}\n"
                f"     Regulatory Authority: {v.statutory_reference}\n"
                f"     Audit Finding: {v.explanation}\n\n"
            )

        signature_status = "VERIFIED_HUMAN_SIGNATURE_TOKEN" if cedar_verified else "PENDING_MEMBER_CONFIRMATION"

        appeal_letter = f"""FORMAL NOTICE OF ADVERSE BENEFIT DETERMINATION DISPUTE
PURSUANT TO ERISA § 503 (29 U.S.C. § 1133) & 29 CFR § 2560.503-1

DATE: {datetime.now(timezone.utc).strftime("%B %d, %Y")}
PACKET REFERENCE: {packet_id}
CLAIM REFERENCE NUMBER: {eob.claim_id}
PATIENT / MEMBER NAME: {eob.patient_name}
PATIENT ID: {eob.patient_id}
HEALTHCARE PROVIDER: {eob.provider_name}
DATE OF SERVICE: {eob.service_date}

ATTN: APPEALS & GRIEVANCE COMMITTEE / CLAIMS REVIEW DEPARTMENT

Dear Claims Administrator,

I am writing to formally dispute the adverse benefit determination and cost-sharing adjudication 
rendered on Claim #{eob.claim_id}. 

A deterministic statutory audit of the line items against the Centers for Medicare & Medicaid Services 
(CMS) National Correct Coding Initiative (NCCI) PTP tables has identified improper unbundled charges 
and/or unlawful patient liability reassignments.

TOTAL BILLED BY PROVIDER:             ${eob.total_billed:,.2f}
ADJUDICATED PATIENT RESPONSIBILITY:    ${audit.total_original_patient_liability:,.2f}
TOTAL UNLAWFUL CHARGES EXCISED:        ${audit.total_excised_amount:,.2f}
CORRECTED LAWFUL PATIENT LIABILITY:    ${audit.revised_patient_liability:,.2f}

DETAILED AUDIT FINDINGS & STATUTORY BASES:
{violations_text}
DEMAND FOR RELIEF UNDER FEDERAL LAW:
Pursuant to 29 CFR § 2560.503-1(h)(2)(iii), I hereby demand:
  1. Immediate re-adjudication of Claim #{eob.claim_id} excising all unbundled and improperly 
     shifted amounts totaling ${audit.total_excised_amount:,.2f}.
  2. Immediate adjustment of provider billing to reflect that unbundled component services are 
     Contractual Obligations (CO) of the participating provider and cannot be balance-billed to the member.
  3. Complete disclosure of all internal claim protocols, fee crosswalks, and NCCI edit rationales 
     relied upon in the initial adverse determination.

Failure to re-adjudicate within statutory time limits (30 days for post-service claims under 
29 CFR § 2560.503-1(i)(1)(i)) will constitute failure to provide a reasonable claims procedure, 
entitling the member to pursue all available remedies under Section 502(a) of ERISA.

Sincerely,

{eob.patient_name} (Member)
Digital Signature Token: {signature_status}
Generated by UNBUNDLE Autonomous EOB Sentinel (Strands Agents SDK + AWS Bedrock AgentCore)
"""

        return AppealPacket(
            packet_id=packet_id,
            claim_id=eob.claim_id,
            generated_at=now_str,
            statutory_citations=citations,
            patient_name=eob.patient_name,
            provider_name=eob.provider_name,
            original_charge=audit.total_original_patient_liability,
            audited_charge=audit.revised_patient_liability,
            disputed_amount=audit.total_excised_amount,
            formal_appeal_letter=appeal_letter.strip(),
            evidence_breakdown=evidence_breakdown,
            cedar_authorization_verified=cedar_verified
        )
